name: Demo Workflow
on: workflow_dispatch

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello World!"
      - name: Greeting 2
        run: echo "Hello World!"
  next-job:
    runs-on: ubuntu-latest
    steps:
      - name: Another Greeting?
        run: echo "whatever"